[contest]
name = "toi-primary-2022-test"
description = "TOI Primary 2022 test"
token_mode = "infinite"

[[contest.users]]
username = "u1"
password = "p1"

[contest-config]
languages = ["C11 / gcc", "C++14 / g++", "Java / JDK", "Python 3 / CPython"]

[contest-config.mapping]
"C11 / gcc" = [".c"]
"C++14 / g++" = [".cpp", ".cc", ".cxx", ".c++", ".C"]
"Java / JDK" = [".java"]
"Python 3 / CPython" = [".py"]

[task_template]
infile = ""
outfile = ""
task_type = "Batch"
score_mode = "max_subtask" # 2017~
token_mode = "infinite"
score_type = "GroupMin"
score_type_parameters = ""
time_limit = 15
memory_limit = 1024

[[tasks]]
name = "2022"
title = "2022"
time_limit = 0.1
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  5 = ["1", "2", "3", "4"]

[[tasks]]
name = "entrance"
title = "entrance"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["1", "2"]

[[tasks]]
name = "keyboard"
title = "keyboard"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["1", "2"]

[[tasks]]
name = "spy"
title = "spy"
time_limit = 0.3
  [tasks.inclusive_tests]
  4 = ["1", "2", "3"]

[[tasks]]
name = "bike"
title = "bike"
time_limit = 1.0
  [tasks.inclusive_tests]
  4 = ["1", "2", "3"]
